// <auto-generated />
using System;
using BusinessModel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessModel.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    [Migration("20250429080129_InitIdentity")]
    partial class InitIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessModel.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OrderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            OrderDate = new DateTime(2023, 1, 1, 16, 12, 59, 0, DateTimeKind.Unspecified),
                            Rating = 6.8f,
                            Status = 0,
                            UserName = "John Doe"
                        });
                });

            modelBuilder.Entity("BusinessModel.Models.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OrderItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("RecipeId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            OrderId = 1L,
                            Quantity = 2,
                            Rating = 5f,
                            RecipeId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            OrderId = 1L,
                            Quantity = 1,
                            Rating = 8.2f,
                            RecipeId = 3L
                        });
                });

            modelBuilder.Entity("BusinessModel.Models.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RecipeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CaloriesPerServing")
                        .HasColumnType("int");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "image");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CaloriesPerServing = 300,
                            CookTimeMinutes = 15,
                            Cuisine = "Italian",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/1.webp",
                            Ingredients = "[\"Pizza dough\",\"Tomato sauce\",\"Fresh mozzarella cheese\",\"Fresh basil leaves\",\"Olive oil\",\"Salt and pepper to taste\"]",
                            Instructions = "[\"Preheat the oven to 475\\u00B0F (245\\u00B0C).\",\"Roll out the pizza dough and spread tomato sauce evenly.\",\"Top with slices of fresh mozzarella and fresh basil leaves.\",\"Drizzle with olive oil and season with salt and pepper.\",\"Bake in the preheated oven for 12-15 minutes or until the crust is golden brown.\",\"Slice and serve hot.\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Classic Margherita Pizza",
                            PrepTimeMinutes = 20,
                            Rating = 4.6f,
                            ReviewCount = 98,
                            Servings = 4,
                            Tags = "[\"Pizza\",\"Italian\"]",
                            UserId = 166
                        },
                        new
                        {
                            Id = 2L,
                            CaloriesPerServing = 250,
                            CookTimeMinutes = 20,
                            Cuisine = "Asian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/2.webp",
                            Ingredients = "[\"Tofu, cubed\",\"Broccoli florets\",\"Carrots, sliced\",\"Bell peppers, sliced\",\"Soy sauce\",\"Ginger, minced\",\"Garlic, minced\",\"Sesame oil\",\"Cooked rice for serving\"]",
                            Instructions = "[\"In a wok, heat sesame oil over medium-high heat.\",\"Add minced ginger and garlic, saut\\u00E9 until fragrant.\",\"Add cubed tofu and stir-fry until golden brown.\",\"Add broccoli, carrots, and bell peppers. Cook until vegetables are tender-crisp.\",\"Pour soy sauce over the stir-fry and toss to combine.\",\"Serve over cooked rice.\"]",
                            MealType = "[\"Lunch\"]",
                            Name = "Vegetarian Stir-Fry",
                            PrepTimeMinutes = 15,
                            Rating = 4.7f,
                            ReviewCount = 26,
                            Servings = 3,
                            Tags = "[\"Vegetarian\",\"Stir-fry\",\"Asian\"]",
                            UserId = 143
                        },
                        new
                        {
                            Id = 3L,
                            CaloriesPerServing = 150,
                            CookTimeMinutes = 10,
                            Cuisine = "American",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/3.webp",
                            Ingredients = "[\"All-purpose flour\",\"Butter, softened\",\"Brown sugar\",\"White sugar\",\"Eggs\",\"Vanilla extract\",\"Baking soda\",\"Salt\",\"Chocolate chips\"]",
                            Instructions = "[\"Preheat the oven to 350\\u00B0F (175\\u00B0C).\",\"In a bowl, cream together softened butter, brown sugar, and white sugar.\",\"Beat in eggs one at a time, then stir in vanilla extract.\",\"Combine flour, baking soda, and salt. Gradually add to the wet ingredients.\",\"Fold in chocolate chips.\",\"Drop rounded tablespoons of dough onto ungreased baking sheets.\",\"Bake for 10-12 minutes or until edges are golden brown.\",\"Allow cookies to cool on the baking sheet for a few minutes before transferring to a wire rack.\"]",
                            MealType = "[\"Snack\",\"Dessert\"]",
                            Name = "Chocolate Chip Cookies",
                            PrepTimeMinutes = 15,
                            Rating = 4.9f,
                            ReviewCount = 13,
                            Servings = 24,
                            Tags = "[\"Cookies\",\"Dessert\",\"Baking\"]",
                            UserId = 34
                        },
                        new
                        {
                            Id = 4L,
                            CaloriesPerServing = 500,
                            CookTimeMinutes = 20,
                            Cuisine = "Italian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/4.webp",
                            Ingredients = "[\"Fettuccine pasta\",\"Chicken breast, sliced\",\"Heavy cream\",\"Parmesan cheese, grated\",\"Garlic, minced\",\"Butter\",\"Salt and pepper to taste\",\"Fresh parsley for garnish\"]",
                            Instructions = "[\"Cook fettuccine pasta according to package instructions.\",\"In a pan, saut\\u00E9 sliced chicken in butter until fully cooked.\",\"Add minced garlic and cook until fragrant.\",\"Pour in heavy cream and grated Parmesan cheese. Stir until the cheese is melted.\",\"Season with salt and pepper to taste.\",\"Combine the Alfredo sauce with cooked pasta.\",\"Garnish with fresh parsley before serving.\"]",
                            MealType = "[\"Lunch\",\"Dinner\"]",
                            Name = "Chicken Alfredo Pasta",
                            PrepTimeMinutes = 15,
                            Rating = 4.9f,
                            ReviewCount = 82,
                            Servings = 4,
                            Tags = "[\"Pasta\",\"Chicken\"]",
                            UserId = 136
                        },
                        new
                        {
                            Id = 5L,
                            CaloriesPerServing = 380,
                            CookTimeMinutes = 25,
                            Cuisine = "Mexican",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/5.webp",
                            Ingredients = "[\"Chicken thighs\",\"Mango, diced\",\"Red onion, finely chopped\",\"Cilantro, chopped\",\"Lime juice\",\"Jalape\\u00F1o, minced\",\"Salt and pepper to taste\",\"Cooked rice for serving\"]",
                            Instructions = "[\"Season chicken thighs with salt and pepper.\",\"Grill or bake chicken until fully cooked.\",\"In a bowl, combine diced mango, chopped red onion, cilantro, minced jalape\\u00F1o, and lime juice.\",\"Dice the cooked chicken and mix it with the mango salsa.\",\"Serve over cooked rice.\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Mango Salsa Chicken",
                            PrepTimeMinutes = 15,
                            Rating = 4.9f,
                            ReviewCount = 63,
                            Servings = 3,
                            Tags = "[\"Chicken\",\"Salsa\"]",
                            UserId = 26
                        },
                        new
                        {
                            Id = 6L,
                            CaloriesPerServing = 280,
                            CookTimeMinutes = 15,
                            Cuisine = "Mediterranean",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/6.webp",
                            Ingredients = "[\"Quinoa, cooked\",\"Avocado, diced\",\"Cherry tomatoes, halved\",\"Cucumber, diced\",\"Red bell pepper, diced\",\"Feta cheese, crumbled\",\"Lemon vinaigrette dressing\",\"Salt and pepper to taste\"]",
                            Instructions = "[\"In a large bowl, combine cooked quinoa, diced avocado, halved cherry tomatoes, diced cucumber, diced red bell pepper, and crumbled feta cheese.\",\"Drizzle with lemon vinaigrette dressing and toss to combine.\",\"Season with salt and pepper to taste.\",\"Chill in the refrigerator before serving.\"]",
                            MealType = "[\"Lunch\",\"Side Dish\"]",
                            Name = "Quinoa Salad with Avocado",
                            PrepTimeMinutes = 20,
                            Rating = 4.4f,
                            ReviewCount = 59,
                            Servings = 4,
                            Tags = "[\"Salad\",\"Quinoa\"]",
                            UserId = 197
                        },
                        new
                        {
                            Id = 7L,
                            CaloriesPerServing = 120,
                            CookTimeMinutes = 10,
                            Cuisine = "Italian",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/7.webp",
                            Ingredients = "[\"Baguette, sliced\",\"Tomatoes, diced\",\"Fresh basil, chopped\",\"Garlic cloves, minced\",\"Balsamic glaze\",\"Olive oil\",\"Salt and pepper to taste\"]",
                            Instructions = "[\"Preheat the oven to 375\\u00B0F (190\\u00B0C).\",\"Place baguette slices on a baking sheet and toast in the oven until golden brown.\",\"In a bowl, combine diced tomatoes, chopped fresh basil, minced garlic, and a drizzle of olive oil.\",\"Season with salt and pepper to taste.\",\"Top each toasted baguette slice with the tomato-basil mixture.\",\"Drizzle with balsamic glaze before serving.\"]",
                            MealType = "[\"Appetizer\"]",
                            Name = "Tomato Basil Bruschetta",
                            PrepTimeMinutes = 15,
                            Rating = 4.7f,
                            ReviewCount = 95,
                            Servings = 6,
                            Tags = "[\"Bruschetta\",\"Italian\"]",
                            UserId = 137
                        },
                        new
                        {
                            Id = 8L,
                            CaloriesPerServing = 380,
                            CookTimeMinutes = 15,
                            Cuisine = "Asian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/8.webp",
                            Ingredients = "[\"Beef sirloin, thinly sliced\",\"Broccoli florets\",\"Soy sauce\",\"Oyster sauce\",\"Sesame oil\",\"Garlic, minced\",\"Ginger, minced\",\"Cornstarch\",\"Cooked white rice for serving\"]",
                            Instructions = "[\"In a bowl, mix soy sauce, oyster sauce, sesame oil, and cornstarch to create the sauce.\",\"In a wok, stir-fry thinly sliced beef until browned. Remove from the wok.\",\"Stir-fry broccoli florets, minced garlic, and minced ginger in the same wok.\",\"Add the cooked beef back to the wok and pour the sauce over the mixture.\",\"Stir until everything is coated and heated through.\",\"Serve over cooked white rice.\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Beef and Broccoli Stir-Fry",
                            PrepTimeMinutes = 20,
                            Rating = 4.7f,
                            ReviewCount = 58,
                            Servings = 4,
                            Tags = "[\"Beef\",\"Stir-fry\",\"Asian\"]",
                            UserId = 18
                        },
                        new
                        {
                            Id = 9L,
                            CaloriesPerServing = 200,
                            CookTimeMinutes = 0,
                            Cuisine = "Italian",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/9.webp",
                            Ingredients = "[\"Tomatoes, sliced\",\"Fresh mozzarella cheese, sliced\",\"Fresh basil leaves\",\"Balsamic glaze\",\"Extra virgin olive oil\",\"Salt and pepper to taste\"]",
                            Instructions = "[\"Arrange alternating slices of tomatoes and fresh mozzarella on a serving platter.\",\"Tuck fresh basil leaves between the slices.\",\"Drizzle with balsamic glaze and extra virgin olive oil.\",\"Season with salt and pepper to taste.\",\"Serve immediately as a refreshing salad.\"]",
                            MealType = "[\"Lunch\"]",
                            Name = "Caprese Salad",
                            PrepTimeMinutes = 10,
                            Rating = 4.6f,
                            ReviewCount = 82,
                            Servings = 2,
                            Tags = "[\"Salad\",\"Caprese\"]",
                            UserId = 128
                        },
                        new
                        {
                            Id = 10L,
                            CaloriesPerServing = 400,
                            CookTimeMinutes = 20,
                            Cuisine = "Italian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/10.webp",
                            Ingredients = "[\"Linguine pasta\",\"Shrimp, peeled and deveined\",\"Garlic, minced\",\"White wine\",\"Lemon juice\",\"Red pepper flakes\",\"Fresh parsley, chopped\",\"Salt and pepper to taste\"]",
                            Instructions = "[\"Cook linguine pasta according to package instructions.\",\"In a skillet, saut\\u00E9 minced garlic in olive oil until fragrant.\",\"Add shrimp and cook until pink and opaque.\",\"Pour in white wine and lemon juice. Simmer until the sauce slightly thickens.\",\"Season with red pepper flakes, salt, and pepper.\",\"Toss cooked linguine in the shrimp scampi sauce.\",\"Garnish with chopped fresh parsley before serving.\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Shrimp Scampi Pasta",
                            PrepTimeMinutes = 15,
                            Rating = 4.3f,
                            ReviewCount = 5,
                            Servings = 3,
                            Tags = "[\"Pasta\",\"Shrimp\"]",
                            UserId = 114
                        },
                        new
                        {
                            Id = 11L,
                            CaloriesPerServing = 550,
                            CookTimeMinutes = 45,
                            Cuisine = "Pakistani",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/11.webp",
                            Ingredients = "[\"Basmati rice\",\"Chicken, cut into pieces\",\"Onions, thinly sliced\",\"Tomatoes, chopped\",\"Yogurt\",\"Ginger-garlic paste\",\"Biryani masala\",\"Green chilies, sliced\",\"Fresh coriander leaves\",\"Mint leaves\",\"Ghee\",\"Salt to taste\"]",
                            Instructions = "[\"Marinate chicken with yogurt, ginger-garlic paste, biryani masala, and salt.\",\"In a pot, saut\\u00E9 sliced onions until golden brown. Remove half for later use.\",\"Layer marinated chicken, chopped tomatoes, half of the fried onions, and rice in the pot.\",\"Top with ghee, green chilies, fresh coriander leaves, mint leaves, and the remaining fried onions.\",\"Cover and cook on low heat until the rice is fully cooked and aromatic.\",\"Serve hot, garnished with additional coriander and mint leaves.\"]",
                            MealType = "[\"Lunch\",\"Dinner\"]",
                            Name = "Chicken Biryani",
                            PrepTimeMinutes = 30,
                            Rating = 5f,
                            ReviewCount = 32,
                            Servings = 6,
                            Tags = "[\"Biryani\",\"Chicken\",\"Main course\",\"Indian\",\"Pakistani\",\"Asian\"]",
                            UserId = 133
                        },
                        new
                        {
                            Id = 12L,
                            CaloriesPerServing = 420,
                            CookTimeMinutes = 30,
                            Cuisine = "Pakistani",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/12.webp",
                            Ingredients = "[\"Chicken, cut into pieces\",\"Tomatoes, chopped\",\"Green chilies, sliced\",\"Ginger, julienned\",\"Garlic, minced\",\"Coriander powder\",\"Cumin powder\",\"Red chili powder\",\"Garam masala\",\"Cooking oil\",\"Fresh coriander leaves\",\"Salt to taste\"]",
                            Instructions = "[\"In a wok (karahi), heat cooking oil and saut\\u00E9 minced garlic until golden brown.\",\"Add chicken pieces and cook until browned on all sides.\",\"Add chopped tomatoes, green chilies, ginger, and spices. Cook until tomatoes are soft.\",\"Cover and simmer until the chicken is tender and the oil separates from the masala.\",\"Garnish with fresh coriander leaves and serve hot with naan or rice.\"]",
                            MealType = "[\"Lunch\",\"Dinner\"]",
                            Name = "Chicken Karahi",
                            PrepTimeMinutes = 20,
                            Rating = 4.8f,
                            ReviewCount = 68,
                            Servings = 4,
                            Tags = "[\"Chicken\",\"Karahi\",\"Main course\",\"Indian\",\"Pakistani\",\"Asian\"]",
                            UserId = 49
                        },
                        new
                        {
                            Id = 13L,
                            CaloriesPerServing = 380,
                            CookTimeMinutes = 35,
                            Cuisine = "Pakistani",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/13.webp",
                            Ingredients = "[\"Ground beef\",\"Potatoes, peeled and diced\",\"Onions, finely chopped\",\"Tomatoes, chopped\",\"Ginger-garlic paste\",\"Cumin powder\",\"Coriander powder\",\"Turmeric powder\",\"Red chili powder\",\"Cooking oil\",\"Fresh coriander leaves\",\"Salt to taste\"]",
                            Instructions = "[\"In a pan, heat cooking oil and saut\\u00E9 chopped onions until golden brown.\",\"Add ginger-garlic paste and saut\\u00E9 until fragrant.\",\"Add ground beef and cook until browned. Drain excess oil if needed.\",\"Add diced potatoes, chopped tomatoes, and spices. Mix well.\",\"Cover and simmer until the potatoes are tender and the masala is well-cooked.\",\"Garnish with fresh coriander leaves and serve hot with naan or rice.\"]",
                            MealType = "[\"Lunch\",\"Dinner\"]",
                            Name = "Aloo Keema",
                            PrepTimeMinutes = 25,
                            Rating = 4.6f,
                            ReviewCount = 53,
                            Servings = 5,
                            Tags = "[\"Keema\",\"Potatoes\",\"Main course\",\"Pakistani\",\"Asian\"]",
                            UserId = 152
                        },
                        new
                        {
                            Id = 14L,
                            CaloriesPerServing = 320,
                            CookTimeMinutes = 20,
                            Cuisine = "Pakistani",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/14.webp",
                            Ingredients = "[\"Ground beef\",\"Onions, finely chopped\",\"Tomatoes, finely chopped\",\"Green chilies, chopped\",\"Coriander leaves, chopped\",\"Pomegranate seeds\",\"Ginger-garlic paste\",\"Cumin powder\",\"Coriander powder\",\"Red chili powder\",\"Egg\",\"Cooking oil\",\"Salt to taste\"]",
                            Instructions = "[\"In a large bowl, mix ground beef, chopped onions, tomatoes, green chilies, coriander leaves, and pomegranate seeds.\",\"Add ginger-garlic paste, cumin powder, coriander powder, red chili powder, and salt. Mix well.\",\"Add an egg to bind the mixture and form into round flat kebabs.\",\"Heat cooking oil in a pan and shallow fry the kebabs until browned on both sides.\",\"Serve hot with naan or mint chutney.\"]",
                            MealType = "[\"Lunch\",\"Dinner\",\"Snacks\"]",
                            Name = "Chapli Kebabs",
                            PrepTimeMinutes = 30,
                            Rating = 4.7f,
                            ReviewCount = 98,
                            Servings = 4,
                            Tags = "[\"Kebabs\",\"Beef\",\"Indian\",\"Pakistani\",\"Asian\"]",
                            UserId = 152
                        },
                        new
                        {
                            Id = 15L,
                            CaloriesPerServing = 280,
                            CookTimeMinutes = 30,
                            Cuisine = "Pakistani",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/15.webp",
                            Ingredients = "[\"Mustard greens, washed and chopped\",\"Spinach, washed and chopped\",\"Cornmeal (makki ka atta)\",\"Onions, finely chopped\",\"Green chilies, chopped\",\"Ginger, grated\",\"Ghee\",\"Salt to taste\"]",
                            Instructions = "[\"Boil mustard greens and spinach until tender. Drain and blend into a coarse paste.\",\"In a pan, saut\\u00E9 chopped onions, green chilies, and grated ginger in ghee until golden brown.\",\"Add the greens paste and cook until it thickens.\",\"Meanwhile, knead cornmeal with water to make a dough. Roll into rotis (flatbreads).\",\"Cook the rotis on a griddle until golden brown.\",\"Serve hot saag with makki di roti and a dollop of ghee.\"]",
                            MealType = "[\"Breakfast\",\"Lunch\",\"Dinner\"]",
                            Name = "Saag (Spinach) with Makki di Roti",
                            PrepTimeMinutes = 40,
                            Rating = 4.3f,
                            ReviewCount = 86,
                            Servings = 3,
                            Tags = "[\"Saag\",\"Roti\",\"Main course\",\"Indian\",\"Pakistani\",\"Asian\"]",
                            UserId = 43
                        },
                        new
                        {
                            Id = 16L,
                            CaloriesPerServing = 480,
                            CookTimeMinutes = 25,
                            Cuisine = "Japanese",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/16.webp",
                            Ingredients = "[\"Ramen noodles\",\"Chicken broth\",\"Soy sauce\",\"Mirin\",\"Sesame oil\",\"Shiitake mushrooms, sliced\",\"Bok choy, chopped\",\"Green onions, sliced\",\"Soft-boiled eggs\",\"Grilled chicken slices\",\"Norwegian seaweed (nori)\"]",
                            Instructions = "[\"Cook ramen noodles according to package instructions and set aside.\",\"In a pot, combine chicken broth, soy sauce, mirin, and sesame oil. Bring to a simmer.\",\"Add sliced shiitake mushrooms and chopped bok choy. Cook until vegetables are tender.\",\"Divide the cooked noodles into serving bowls and ladle the hot broth over them.\",\"Top with green onions, soft-boiled eggs, grilled chicken slices, and nori.\",\"Serve hot and enjoy the authentic Japanese ramen!\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Japanese Ramen Soup",
                            PrepTimeMinutes = 20,
                            Rating = 4.9f,
                            ReviewCount = 38,
                            Servings = 2,
                            Tags = "[\"Ramen\",\"Japanese\",\"Soup\",\"Asian\"]",
                            UserId = 85
                        },
                        new
                        {
                            Id = 17L,
                            CaloriesPerServing = 320,
                            CookTimeMinutes = 30,
                            Cuisine = "Moroccan",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/17.webp",
                            Ingredients = "[\"Chickpeas, cooked\",\"Tomatoes, chopped\",\"Carrots, diced\",\"Onions, finely chopped\",\"Garlic, minced\",\"Cumin\",\"Coriander\",\"Cinnamon\",\"Paprika\",\"Vegetable broth\",\"Olives\",\"Fresh cilantro, chopped\"]",
                            Instructions = "[\"In a tagine or large pot, saut\\u00E9 chopped onions and minced garlic until softened.\",\"Add diced carrots, chopped tomatoes, and cooked chickpeas.\",\"Season with cumin, coriander, cinnamon, and paprika. Stir to coat.\",\"Pour in vegetable broth and bring to a simmer. Cook until carrots are tender.\",\"Stir in olives and garnish with fresh cilantro before serving.\",\"Serve this flavorful Moroccan dish with couscous or crusty bread.\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Moroccan Chickpea Tagine",
                            PrepTimeMinutes = 15,
                            Rating = 4.5f,
                            ReviewCount = 50,
                            Servings = 4,
                            Tags = "[\"Tagine\",\"Chickpea\",\"Moroccan\"]",
                            UserId = 207
                        },
                        new
                        {
                            Id = 18L,
                            CaloriesPerServing = 550,
                            CookTimeMinutes = 20,
                            Cuisine = "Korean",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/18.webp",
                            Ingredients = "[\"Cooked white rice\",\"Beef bulgogi (marinated and grilled beef slices)\",\"Carrots, julienned and saut\\u00E9ed\",\"Spinach, blanched and seasoned\",\"Zucchini, sliced and grilled\",\"Bean sprouts, blanched\",\"Fried egg\",\"Gochujang (Korean red pepper paste)\",\"Sesame oil\",\"Toasted sesame seeds\"]",
                            Instructions = "[\"Arrange cooked white rice in a bowl.\",\"Top with beef bulgogi, saut\\u00E9ed carrots, seasoned spinach, grilled zucchini, and blanched bean sprouts.\",\"Place a fried egg on top and drizzle with gochujang and sesame oil.\",\"Sprinkle with toasted sesame seeds before serving.\",\"Mix everything together before enjoying this delicious Korean bibimbap!\",\"Feel free to customize with additional vegetables or protein.\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Korean Bibimbap",
                            PrepTimeMinutes = 30,
                            Rating = 4.9f,
                            ReviewCount = 56,
                            Servings = 2,
                            Tags = "[\"Bibimbap\",\"Korean\",\"Rice\"]",
                            UserId = 121
                        },
                        new
                        {
                            Id = 19L,
                            CaloriesPerServing = 420,
                            CookTimeMinutes = 45,
                            Cuisine = "Greek",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/19.webp",
                            Ingredients = "[\"Eggplants, sliced\",\"Ground lamb or beef\",\"Onions, finely chopped\",\"Garlic, minced\",\"Tomatoes, crushed\",\"Red wine\",\"Cinnamon\",\"Allspice\",\"Nutmeg\",\"Olive oil\",\"Milk\",\"Flour\",\"Parmesan cheese\",\"Egg yolks\"]",
                            Instructions = "[\"Preheat oven to 375\\u00B0F (190\\u00B0C).\",\"Saut\\u00E9 sliced eggplants in olive oil until browned. Set aside.\",\"In the same pan, cook chopped onions and minced garlic until softened.\",\"Add ground lamb or beef and brown. Stir in crushed tomatoes, red wine, and spices.\",\"In a separate saucepan, make b\\u00E9chamel sauce: melt butter, whisk in flour, add milk, and cook until thickened.\",\"Remove from heat and stir in Parmesan cheese and egg yolks.\",\"In a baking dish, layer eggplants and meat mixture. Top with b\\u00E9chamel sauce.\",\"Bake for 40-45 minutes until golden brown. Let it cool before slicing.\",\"Serve slices of moussaka warm and enjoy this Greek classic!\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Greek Moussaka",
                            PrepTimeMinutes = 45,
                            Rating = 4.3f,
                            ReviewCount = 26,
                            Servings = 6,
                            Tags = "[\"Moussaka\",\"Greek\"]",
                            UserId = 173
                        },
                        new
                        {
                            Id = 20L,
                            CaloriesPerServing = 480,
                            CookTimeMinutes = 25,
                            Cuisine = "Pakistani",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/20.webp",
                            Ingredients = "[\"Chicken thighs, boneless and skinless\",\"Yogurt\",\"Ginger-garlic paste\",\"Garam masala\",\"Kashmiri red chili powder\",\"Tomato puree\",\"Butter\",\"Heavy cream\",\"Kasuri methi (dried fenugreek leaves)\",\"Sugar\",\"Salt to taste\"]",
                            Instructions = "[\"Marinate chicken thighs in a mixture of yogurt, ginger-garlic paste, garam masala, and Kashmiri red chili powder.\",\"In a pan, melt butter and saut\\u00E9 the marinated chicken until browned.\",\"Add tomato puree and cook until the oil separates. Stir in heavy cream.\",\"Sprinkle kasuri methi, sugar, and salt. Simmer until the chicken is fully cooked.\",\"Serve this creamy butter chicken over rice or with naan for an authentic Pakistani/Indian experience.\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Butter Chicken (Murgh Makhani)",
                            PrepTimeMinutes = 30,
                            Rating = 4.5f,
                            ReviewCount = 44,
                            Servings = 4,
                            Tags = "[\"Butter chicken\",\"Curry\",\"Indian\",\"Pakistani\",\"Asian\"]",
                            UserId = 138
                        },
                        new
                        {
                            Id = 21L,
                            CaloriesPerServing = 480,
                            CookTimeMinutes = 30,
                            Cuisine = "Thai",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/21.webp",
                            Ingredients = "[\"Chicken thighs, boneless and skinless\",\"Green curry paste\",\"Coconut milk\",\"Fish sauce\",\"Sugar\",\"Eggplant, sliced\",\"Bell peppers, sliced\",\"Basil leaves\",\"Jasmine rice for serving\"]",
                            Instructions = "[\"In a pot, simmer green curry paste in coconut milk.\",\"Add chicken, fish sauce, and sugar. Cook until chicken is tender.\",\"Stir in sliced eggplant and bell peppers. Simmer until vegetables are cooked.\",\"Garnish with fresh basil leaves.\",\"Serve hot over jasmine rice and enjoy this Thai classic!\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Thai Green Curry",
                            PrepTimeMinutes = 20,
                            Rating = 4.2f,
                            ReviewCount = 18,
                            Servings = 4,
                            Tags = "[\"Curry\",\"Thai\"]",
                            UserId = 153
                        },
                        new
                        {
                            Id = 22L,
                            CaloriesPerServing = 180,
                            CookTimeMinutes = 0,
                            Cuisine = "Indian",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/22.webp",
                            Ingredients = "[\"Ripe mango, peeled and diced\",\"Yogurt\",\"Milk\",\"Honey\",\"Cardamom powder\",\"Ice cubes\"]",
                            Instructions = "[\"In a blender, combine diced mango, yogurt, milk, honey, and cardamom powder.\",\"Blend until smooth and creamy.\",\"Add ice cubes and blend again until the lassi is chilled.\",\"Pour into glasses and garnish with a sprinkle of cardamom.\",\"Enjoy this refreshing Mango Lassi!\"]",
                            MealType = "[\"Beverage\"]",
                            Name = "Mango Lassi",
                            PrepTimeMinutes = 10,
                            Rating = 4.7f,
                            ReviewCount = 15,
                            Servings = 2,
                            Tags = "[\"Lassi\",\"Mango\",\"Indian\",\"Pakistani\",\"Asian\"]",
                            UserId = 76
                        },
                        new
                        {
                            Id = 23L,
                            CaloriesPerServing = 350,
                            CookTimeMinutes = 0,
                            Cuisine = "Italian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/23.webp",
                            Ingredients = "[\"Espresso, brewed and cooled\",\"Ladyfinger cookies\",\"Mascarpone cheese\",\"Heavy cream\",\"Sugar\",\"Cocoa powder\"]",
                            Instructions = "[\"In a bowl, whip heavy cream until stiff peaks form.\",\"In another bowl, mix mascarpone cheese and sugar until smooth.\",\"Gently fold the whipped cream into the mascarpone mixture.\",\"Dip ladyfinger cookies into brewed espresso and layer them in a serving dish.\",\"Spread a layer of the mascarpone mixture over the cookies.\",\"Repeat layers and finish with a dusting of cocoa powder.\",\"Chill in the refrigerator for a few hours before serving.\",\"Indulge in the decadence of this classic Italian Tiramisu!\"]",
                            MealType = "[\"Dessert\"]",
                            Name = "Italian Tiramisu",
                            PrepTimeMinutes = 30,
                            Rating = 4.6f,
                            ReviewCount = 0,
                            Servings = 6,
                            Tags = "[\"Tiramisu\",\"Italian\"]",
                            UserId = 130
                        },
                        new
                        {
                            Id = 24L,
                            CaloriesPerServing = 280,
                            CookTimeMinutes = 15,
                            Cuisine = "Turkish",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/24.webp",
                            Ingredients = "[\"Ground lamb or beef\",\"Onions, grated\",\"Garlic, minced\",\"Parsley, finely chopped\",\"Cumin\",\"Coriander\",\"Red pepper flakes\",\"Salt and pepper to taste\",\"Flatbread for serving\",\"Tahini sauce\"]",
                            Instructions = "[\"In a bowl, mix ground meat, grated onions, minced garlic, chopped parsley, and spices.\",\"Form the mixture into kebab shapes and grill until fully cooked.\",\"Serve the kebabs on flatbread with a drizzle of tahini sauce.\",\"Enjoy these flavorful Turkish Kebabs with your favorite sides.\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Turkish Kebabs",
                            PrepTimeMinutes = 25,
                            Rating = 4.6f,
                            ReviewCount = 78,
                            Servings = 4,
                            Tags = "[\"Kebabs\",\"Turkish\",\"Grilling\"]",
                            UserId = 26
                        },
                        new
                        {
                            Id = 25L,
                            CaloriesPerServing = 220,
                            CookTimeMinutes = 0,
                            Cuisine = "Smoothie",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/25.webp",
                            Ingredients = "[\"Blueberries, fresh or frozen\",\"Banana, peeled and sliced\",\"Greek yogurt\",\"Almond milk\",\"Honey\",\"Chia seeds (optional)\"]",
                            Instructions = "[\"In a blender, combine blueberries, banana, Greek yogurt, almond milk, and honey.\",\"Blend until smooth and creamy.\",\"Add chia seeds for extra nutrition and blend briefly.\",\"Pour into a glass and enjoy this nutritious Blueberry Banana Smoothie!\"]",
                            MealType = "[\"Breakfast\",\"Beverage\"]",
                            Name = "Blueberry Banana Smoothie",
                            PrepTimeMinutes = 10,
                            Rating = 4.8f,
                            ReviewCount = 30,
                            Servings = 1,
                            Tags = "[\"Smoothie\",\"Blueberry\",\"Banana\"]",
                            UserId = 16
                        },
                        new
                        {
                            Id = 26L,
                            CaloriesPerServing = 180,
                            CookTimeMinutes = 15,
                            Cuisine = "Mexican",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/26.webp",
                            Ingredients = "[\"Corn on the cob\",\"Mayonnaise\",\"Cotija cheese, crumbled\",\"Chili powder\",\"Lime wedges\"]",
                            Instructions = "[\"Grill or roast corn on the cob until kernels are charred.\",\"Brush each cob with mayonnaise, then sprinkle with crumbled Cotija cheese and chili powder.\",\"Serve with lime wedges for squeezing over the top.\",\"Enjoy this delicious and flavorful Mexican Street Corn!\"]",
                            MealType = "[\"Snack\",\"Side Dish\"]",
                            Name = "Mexican Street Corn (Elote)",
                            PrepTimeMinutes = 15,
                            Rating = 4.6f,
                            ReviewCount = 2,
                            Servings = 4,
                            Tags = "[\"Elote\",\"Mexican\",\"Street food\"]",
                            UserId = 93
                        },
                        new
                        {
                            Id = 27L,
                            CaloriesPerServing = 220,
                            CookTimeMinutes = 40,
                            Cuisine = "Russian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/27.webp",
                            Ingredients = "[\"Beets, peeled and shredded\",\"Cabbage, shredded\",\"Potatoes, diced\",\"Onions, finely chopped\",\"Carrots, grated\",\"Tomato paste\",\"Beef or vegetable broth\",\"Garlic, minced\",\"Bay leaves\",\"Sour cream for serving\"]",
                            Instructions = "[\"In a pot, saut\\u00E9 chopped onions and garlic until softened.\",\"Add shredded beets, cabbage, diced potatoes, grated carrots, and tomato paste.\",\"Pour in broth and add bay leaves. Simmer until vegetables are tender.\",\"Serve hot with a dollop of sour cream on top.\",\"Enjoy the hearty and comforting flavors of Russian Borscht!\"]",
                            MealType = "[\"Dinner\"]",
                            Name = "Russian Borscht",
                            PrepTimeMinutes = 30,
                            Rating = 4.3f,
                            ReviewCount = 39,
                            Servings = 6,
                            Tags = "[\"Borscht\",\"Russian\",\"Soup\"]",
                            UserId = 1
                        },
                        new
                        {
                            Id = 28L,
                            CaloriesPerServing = 320,
                            CookTimeMinutes = 20,
                            Cuisine = "Indian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/28.webp",
                            Ingredients = "[\"Dosa batter (fermented rice and urad dal batter)\",\"Potatoes, boiled and mashed\",\"Onions, finely chopped\",\"Mustard seeds\",\"Cumin seeds\",\"Curry leaves\",\"Turmeric powder\",\"Green chilies, chopped\",\"Ghee\",\"Coconut chutney for serving\"]",
                            Instructions = "[\"In a pan, heat ghee and add mustard seeds, cumin seeds, and curry leaves.\",\"Add chopped onions, green chilies, and turmeric powder. Saut\\u00E9 until onions are golden brown.\",\"Mix in boiled and mashed potatoes. Cook until well combined and seasoned.\",\"Spread dosa batter on a hot griddle to make thin pancakes.\",\"Place a spoonful of the potato mixture in the center, fold, and serve hot.\",\"Pair with coconut chutney for a delicious South Indian meal.\"]",
                            MealType = "[\"Breakfast\"]",
                            Name = "South Indian Masala Dosa",
                            PrepTimeMinutes = 40,
                            Rating = 4.4f,
                            ReviewCount = 96,
                            Servings = 4,
                            Tags = "[\"Dosa\",\"Indian\",\"Asian\"]",
                            UserId = 138
                        },
                        new
                        {
                            Id = 29L,
                            CaloriesPerServing = 400,
                            CookTimeMinutes = 10,
                            Cuisine = "Lebanese",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/29.webp",
                            Ingredients = "[\"Falafel balls\",\"Whole wheat or regular wraps\",\"Tomatoes, diced\",\"Cucumbers, sliced\",\"Red onions, thinly sliced\",\"Lettuce, shredded\",\"Tahini sauce\",\"Fresh parsley, chopped\"]",
                            Instructions = "[\"Warm falafel balls according to package instructions.\",\"Place a generous serving of falafel in the center of each wrap.\",\"Top with diced tomatoes, sliced cucumbers, red onions, shredded lettuce, and fresh parsley.\",\"Drizzle with tahini sauce and wrap tightly.\",\"Enjoy this Lebanese Falafel Wrap filled with fresh and flavorful ingredients!\"]",
                            MealType = "[\"Lunch\"]",
                            Name = "Lebanese Falafel Wrap",
                            PrepTimeMinutes = 15,
                            Rating = 4.7f,
                            ReviewCount = 84,
                            Servings = 2,
                            Tags = "[\"Falafel\",\"Lebanese\",\"Wrap\"]",
                            UserId = 110
                        },
                        new
                        {
                            Id = 30L,
                            CaloriesPerServing = 150,
                            CookTimeMinutes = 0,
                            Cuisine = "Brazilian",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/30.webp",
                            Ingredients = "[\"Cacha\\u00E7a (Brazilian sugarcane spirit)\",\"Lime, cut into wedges\",\"Granulated sugar\",\"Ice cubes\"]",
                            Instructions = "[\"In a glass, muddle lime wedges with granulated sugar to release the juice.\",\"Fill the glass with ice cubes.\",\"Pour cacha\\u00E7a over the ice and stir well.\",\"Sip and enjoy the refreshing taste of the Brazilian Caipirinha!\",\"Adjust sugar and lime to suit your taste preferences.\"]",
                            MealType = "[\"Beverage\"]",
                            Name = "Brazilian Caipirinha",
                            PrepTimeMinutes = 5,
                            Rating = 4.4f,
                            ReviewCount = 55,
                            Servings = 1,
                            Tags = "[\"Caipirinha\",\"Brazilian\",\"Cocktail\"]",
                            UserId = 134
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d4e8321b-447b-43d2-bdce-f4738b588bec",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "eb6b2a41-9e08-4243-bf9b-74f5ac6d9297",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3a32e868-9191-4c77-a8ea-4c825571b5bf",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "79e1071a-9acf-47ba-b7f8-83b367423d97",
                            Email = "root@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ROOT@EXAMPLE.COM",
                            NormalizedUserName = "R. ROOT",
                            PasswordHash = "AQAAAAIAAYagAAAAEI9bnzxidZZ+yhCWxSEb3S6FK1cSyK/2GPjRLnssQErapeLrjxRDdlzL22WyyowLRA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "402771f9-5812-4ae1-b4c0-d6dca0c3e9b7",
                            TwoFactorEnabled = false,
                            UserName = "R. Root"
                        },
                        new
                        {
                            Id = "4b43c757-9e01-4243-bf9b-f4738b588bec",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f2e12cf2-deb7-46d1-b1d6-db5d6ff47473",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN DOE",
                            PasswordHash = "AQAAAAIAAYagAAAAEI9bnzxidZZ+yhCWxSEb3S6FK1cSyK/2GPjRLnssQErapeLrjxRDdlzL22WyyowLRA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "969b06a3-e127-45f4-99fb-237e57c651b9",
                            TwoFactorEnabled = false,
                            UserName = "John Doe"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3a32e868-9191-4c77-a8ea-4c825571b5bf",
                            RoleId = "d4e8321b-447b-43d2-bdce-f4738b588bec"
                        },
                        new
                        {
                            UserId = "4b43c757-9e01-4243-bf9b-f4738b588bec",
                            RoleId = "eb6b2a41-9e08-4243-bf9b-74f5ac6d9297"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BusinessModel.Models.OrderItem", b =>
                {
                    b.HasOne("BusinessModel.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessModel.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessModel.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
