// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NorthwindWebApp.Models;

[Keyless]
public partial class CustomerAndSuppliersByCity
{
    [StringLength(15)]
    public string City { get; set; }

    [Required]
    [StringLength(40)]
    public string CompanyName { get; set; }

    [StringLength(30)]
    public string ContactName { get; set; }

    [Required]
    [StringLength(9)]
    [Unicode(false)]
    public string Relationship { get; set; }
}